/**
 * @fileoverview Database migration runner.
 *
 * Two-phase migration:
 * 1. Drizzle ORM migrations — schema DDL generated by `drizzle-kit generate`.
 * 2. Raw SQL post-migration — extensions, triggers, and functions that Drizzle
 *    doesn't manage natively.
 *
 * Usage: `npm run db:migrate` or `tsx src/db/migrate.ts`
 */

import pg from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';

// ─── Configuration ──────────────────────────────────────────────────────────────

const DATABASE_URL = process.env.DATABASE_URL;

if (!DATABASE_URL) {
  console.error('❌ DATABASE_URL environment variable is required');
  process.exit(1);
}

// ─── Raw SQL: Extensions ────────────────────────────────────────────────────────

const SQL_EXTENSIONS = `
-- pgcrypto: gen_random_uuid(), pgp_sym_encrypt/decrypt
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pg_trgm: trigram-based fuzzy text search (used with GIN indexes)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- pg_stat_statements: query performance monitoring
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
`;

// ─── Raw SQL: updated_at trigger function ───────────────────────────────────────

/**
 * Reusable trigger function that sets `updated_at = NOW()` on every UPDATE.
 * Attached to all tables that have an `updated_at` column.
 */
const SQL_UPDATED_AT_FUNCTION = `
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
`;

/**
 * Tables that need the auto-update trigger on `updated_at`.
 * The trigger name is deterministic so CREATE OR REPLACE (via DROP + CREATE) is idempotent.
 */
const TABLES_WITH_UPDATED_AT = [
  'organizations',
  'users',
  'sessions',
  'contacts',
  'chats',
  'messages',
  'webhooks',
];

function buildUpdatedAtTriggers(): string {
  return TABLES_WITH_UPDATED_AT.map(
    (table) => `
DROP TRIGGER IF EXISTS trg_${table}_updated_at ON ${table};
CREATE TRIGGER trg_${table}_updated_at
  BEFORE UPDATE ON ${table}
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
`,
  ).join('\n');
}

// ─── Raw SQL: tsvector trigger for full-text search on messages ─────────────────

/**
 * Converts the messages.content column to a tsvector and stores it in
 * content_vector. Uses 'english' dictionary by default.
 *
 * Note: The `content_vector` column is defined as TEXT in the Drizzle schema
 * for ORM compatibility. This migration alters it to the actual tsvector type
 * and creates a GIN index on it.
 */
const SQL_MESSAGES_FTS = `
-- Alter content_vector column to actual tsvector type (idempotent via exception handling)
DO $$
BEGIN
  ALTER TABLE messages ALTER COLUMN content_vector TYPE tsvector USING content_vector::tsvector;
EXCEPTION
  WHEN others THEN
    -- Column is already tsvector or doesn't exist yet, skip
    NULL;
END $$;

-- GIN index on the tsvector column for full-text search
CREATE INDEX IF NOT EXISTS idx_messages_content_vector_gin
  ON messages USING gin(content_vector);

-- Trigger function: auto-populate content_vector from content
CREATE OR REPLACE FUNCTION messages_content_vector_update()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.content IS NOT NULL THEN
    NEW.content_vector = to_tsvector('english', NEW.content);
  ELSE
    NEW.content_vector = NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_messages_content_vector ON messages;
CREATE TRIGGER trg_messages_content_vector
  BEFORE INSERT OR UPDATE OF content ON messages
  FOR EACH ROW
  EXECUTE FUNCTION messages_content_vector_update();
`;

// ─── Raw SQL: on_new_message trigger ────────────────────────────────────────────

/**
 * When a new message is inserted, this trigger:
 * 1. Updates chats.last_message_preview with a truncated preview of the content.
 * 2. Updates chats.last_message_at to the message's created_at.
 * 3. Increments chats.unread_count if the message is not from us.
 * 4. Fires pg_notify('new_message', ...) with a JSON payload for real-time push.
 *
 * pg_notify is used instead of polling — the WebSocket server LISTENs on 'new_message'.
 */
const SQL_ON_NEW_MESSAGE = `
CREATE OR REPLACE FUNCTION on_new_message()
RETURNS TRIGGER AS $$
BEGIN
  -- Skip if this is a bulk history sync insert to prevent database lock contention and pg_notify event storms
  IF current_setting('app.is_history_sync', true) = 'true' THEN
    RETURN NEW;
  END IF;

  -- Update chat denormalized fields
  UPDATE chats SET
    last_message_preview = CASE
      WHEN NEW.message_type = 'image' THEN COALESCE('📷 ' || LEFT(NEW.content, 190), '📷 Photo')
      WHEN NEW.message_type = 'video' THEN COALESCE('🎬 ' || LEFT(NEW.content, 190), '🎬 Video')
      WHEN NEW.message_type = 'audio' THEN '🎤 Voice message'
      WHEN NEW.message_type = 'document' THEN COALESCE('📄 ' || LEFT(COALESCE(NEW.metadata->>'fileName', NEW.content, 'Document'), 190))
      WHEN NEW.message_type = 'sticker' THEN '🎭 Sticker'
      WHEN NEW.message_type = 'location' THEN '📍 Location'
      WHEN NEW.message_type = 'contact' THEN '👤 Contact'
      WHEN NEW.message_type = 'call' THEN COALESCE('📞 ' || LEFT(NEW.content, 190), '📞 Call')
      WHEN NEW.message_type = 'poll' THEN COALESCE('📊 ' || LEFT(NEW.content, 190), '📊 Poll')
      WHEN NEW.message_type = 'reaction' THEN COALESCE(LEFT(NEW.content, 10) || ' Reaction', '👍 Reaction')
      WHEN NEW.message_type = 'system' THEN NULL
      ELSE LEFT(NEW.content, 200)
    END,
    last_message_at = NEW.created_at,
    unread_count = CASE
      WHEN NEW.from_me = true THEN 0
      ELSE unread_count + 1
    END,
    updated_at = NOW()
  WHERE id = NEW.chat_id;

  -- Notify listeners with message metadata (no sensitive content in payload)
  PERFORM pg_notify('new_message', json_build_object(
    'messageId', NEW.id,
    'chatId', NEW.chat_id,
    'sessionId', NEW.session_id,
    'orgId', NEW.org_id,
    'messageType', NEW.message_type,
    'fromMe', NEW.from_me,
    'createdAt', NEW.created_at
  )::text);

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_on_new_message ON messages;
CREATE TRIGGER trg_on_new_message
  AFTER INSERT ON messages
  FOR EACH ROW
  EXECUTE FUNCTION on_new_message();
`;

const SQL_CLEANUP_LID_DUPLICATES = `
DO $$
DECLARE
  r RECORD;
  lid_chat_id UUID;
  phone_chat_id UUID;
  new_unread INT;
  new_last_msg_at TIMESTAMPTZ;
  new_last_msg_preview TEXT;
BEGIN
  FOR r IN 
    SELECT c.session_id, c.org_id, c.wa_id AS phone_jid, c.metadata->>'lid' AS lid_jid
    FROM contacts c
    WHERE c.wa_id LIKE '%@s.whatsapp.net' AND c.metadata->>'lid' LIKE '%@lid'
  LOOP
    -- Get the LID chat ID if it exists
    SELECT id, last_message_at, last_message_preview, unread_count
    INTO lid_chat_id, new_last_msg_at, new_last_msg_preview, new_unread
    FROM chats
    WHERE org_id = r.org_id AND session_id = r.session_id AND wa_chat_id = r.lid_jid;

    -- Get the Phone chat ID if it exists
    SELECT id INTO phone_chat_id
    FROM chats
    WHERE org_id = r.org_id AND session_id = r.session_id AND wa_chat_id = r.phone_jid;

    IF lid_chat_id IS NOT NULL THEN
      IF phone_chat_id IS NOT NULL THEN
        -- Move messages (deleting conflicts first)
        DELETE FROM messages 
        WHERE org_id = r.org_id
          AND chat_id = lid_chat_id
          AND wa_message_id IN (
            SELECT wa_message_id FROM messages WHERE org_id = r.org_id AND chat_id = phone_chat_id
          );

        UPDATE messages 
        SET chat_id = phone_chat_id, updated_at = NOW() 
        WHERE org_id = r.org_id AND chat_id = lid_chat_id;

        -- Update phone chat with merged counts/timestamps
        UPDATE chats
        SET 
          unread_count = unread_count + new_unread,
          last_message_at = CASE 
            WHEN new_last_msg_at IS NULL THEN last_message_at
            WHEN last_message_at IS NULL THEN new_last_msg_at
            WHEN new_last_msg_at > last_message_at THEN new_last_msg_at
            ELSE last_message_at
          END,
          last_message_preview = CASE 
            WHEN new_last_msg_at IS NULL THEN last_message_preview
            WHEN last_message_at IS NULL THEN new_last_msg_preview
            WHEN new_last_msg_at > last_message_at THEN new_last_msg_preview
            ELSE last_message_preview
          END,
          updated_at = NOW()
        WHERE id = phone_chat_id;

        -- Delete the duplicate LID chat
        DELETE FROM chats WHERE id = lid_chat_id;
      ELSE
        -- If phone chat doesn't exist, simply rename the LID chat to Phone JID
        UPDATE chats 
        SET wa_chat_id = r.phone_jid, updated_at = NOW() 
        WHERE id = lid_chat_id;
      END IF;
    END IF;
  END LOOP;
END $$;
`;

// ─── Migration Runner ───────────────────────────────────────────────────────────

async function runMigrations(): Promise<void> {
  const pool = new pg.Pool({
    connectionString: DATABASE_URL,
    max: 1, // Single connection for migrations
  });

  try {
    console.log('🚀 Starting database migration...\n');

    // Phase 1: Run Drizzle ORM migrations
    console.log('📦 Phase 1: Running Drizzle schema migrations...');
    const db = drizzle(pool);
    await migrate(db, { migrationsFolder: './src/db/migrations' });
    console.log('✅ Drizzle migrations complete.\n');

    // Phase 2: Run raw SQL post-migration scripts
    console.log('🔧 Phase 2: Applying extensions and triggers...');
    const client = await pool.connect();

    try {
      await client.query('BEGIN');

      // Extensions (each is idempotent with IF NOT EXISTS)
      console.log('  → Installing PostgreSQL extensions...');
      await client.query(SQL_EXTENSIONS);

      // updated_at trigger function + triggers on all tables
      console.log('  → Creating updated_at trigger function...');
      await client.query(SQL_UPDATED_AT_FUNCTION);

      console.log('  → Attaching updated_at triggers to tables...');
      await client.query(buildUpdatedAtTriggers());

      // Full-text search on messages
      console.log('  → Setting up messages full-text search trigger...');
      await client.query(SQL_MESSAGES_FTS);

      // on_new_message trigger
      console.log('  → Creating on_new_message trigger...');
      await client.query(SQL_ON_NEW_MESSAGE);

      // Cleanup existing duplicate LID chats/contacts
      console.log('  → Merging existing duplicate LID chats and contacts...');
      await client.query(SQL_CLEANUP_LID_DUPLICATES);

      await client.query('COMMIT');
      console.log('✅ Extensions and triggers applied.\n');
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }

    console.log('🎉 All migrations completed successfully!');
  } catch (error) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

// Execute if run directly (not imported)
runMigrations();
